name: Stakgraph Unit Test
on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Enable docker.host.internal for Ubuntu
        run: |
          pwd && sudo bash -c 'echo "172.17.0.1 host.docker.internal" >> /etc/hosts'

      - name: Checkout from Github
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Verify Go Installation
        run: go version

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Verify gopls Installation
        run: |
          echo "$HOME/go/bin" >> $GITHUB_PATH
          gopls version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify Node.js Installation
        run: node -v

      - name: Install TypeScript and TypeScript LSP
        run: |
          npm install -g typescript typescript-language-server
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Verify TypeScript Installation
        run: |
          tsc --version
          typescript-language-server --version

      - name: Run rust test
        run: cargo test

      # Install Java, kotlin-language-server, and Ruby LSPs so USE_LSP=true tests can spawn language servers
      - name: Install OpenJDK 17 and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk jq unzip curl

      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
          java -version

      - name: Set up local Ruby environment (avoid permission issues)
        run: |
          echo "GEM_HOME=$HOME/.gem" >> $GITHUB_ENV
          echo "PATH=$HOME/.gem/bin:$PATH" >> $GITHUB_ENV

      - name: Install Ruby and Ruby LSPs (match Dockerfile)
        env:
          GEM_HOME: $HOME/.gem
          PATH: $HOME/.gem/bin:$PATH
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install --no-document ruby-lsp solargraph bundler
          ruby -v || true
          which ruby-lsp || true
          ruby-lsp --version || true

      - name: Verify LSP installations are in PATH
        env:
          PATH: $HOME/.gem/bin:$PATH
        run: |
          echo "Current PATH: $PATH"
          echo "ls $HOME/.gem/bin:"
          ls -la $HOME/.gem/bin || true
          which solargraph || echo "solargraph not found in PATH"
          which ruby-lsp || echo "ruby-lsp not found in PATH"
          ruby-lsp --version || echo "ruby-lsp --version failed"

      - name: Run rust test with LSP
        run: USE_LSP=true cargo test -- --test-threads=1